### ISSUE TITLE
Contentful structure

### ISSUE THREAD

**Issue by venelinn** [iammatthias/Cali-Meets-Delhi#13]
Hi Matthias,

Amazing site!

Question? 
Could you provide the Contentful structure you're referring to?
Same as this one:
[https://github.com/iammatthias/.com/issues/18](url)

Thank you !

**Comment by iammatthias** [comment]
https://github.com/iammatthias/Cali-Meets-Delhi/blob/master/src/pages/index.js


It’s all there in the GraphQL query! Tbh there are better ways of setting this up. I’d suggest checking out the Gatsby + Contentful `rich text` support.

**Comment by iammatthias** [comment]
https://github.com/iammatthias/Cali-Meets-Delhi/blob/master/src/pages/index.js


It’s all there in the GraphQL query! Tbh there are better ways of setting this up. I’d suggest checking out the Gatsby + Contentful `rich text` support: https://www.gatsbyjs.org/packages/gatsby-source-contentful/#contentful-rich-text

**Comment by venelinn** [comment]
Hi again!
Thank for the references !
But I'm still new in GraphQL and It's hard to understand the structure.
So you have Model for each Section and then each section has own content model?? Am I right?

The only thing I'm not getting is the connection.

``modules {
         __typename
           ... on ContentfulHero {
          title
``

Thank you !

**Comment by iammatthias** [comment]
```
query Index {
    allContentfulSection {
      edges {
        node {
          id
          title
          slug
          modules {
            __typename
            ... on ContentfulHero {
              title
              image {
                title
                fluid(maxWidth: 1200, quality: 80) {
                  ...GatsbyContentfulFluid_withWebp_noBase64
                }
              }
              logo {
                title
                description
                fluid(maxWidth: 800, quality: 80) {
                  ...GatsbyContentfulFluid_withWebp_noBase64
                }
              }
            }
         
```

So there is `ContentfulSection`, which is a content type with the following blocks: title, slug, and modules. Title is the page title/site title, slug isn’t really needed for this, and modules is a reference field. 

Modules then references other content types. So `modules { __typename ... on ContentfulHero { title` is looking for the section title of the ContentfulHero content type. The rest of the GraphQL query pulls in other stuff from the Hero block - the hero image itself, and the “We’re Getting Married” image overlay. The rest of the query pulls in the other modules, like the Agenda section. 

The problem with this module format is that it is ridged. If you want to change the order of the modules, you need to change the order in Contentful AND in your source code(in the modules component).
